from enum import StrEnum


class ProcessingState(StrEnum):
    RECEIVED = "RECEIVED"
    AWAITING_OCR = "AWAITING_OCR"
    OCR_RECEIVED = "OCR_RECEIVED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    CP_PROCESSING = "CP_PROCESSING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"


class RoutingType(StrEnum):
    INTERNAL = "INTERNAL"
    EXTERNAL = "EXTERNAL"


class CoverSheetAction(StrEnum):
    PROCESS_THROUGH_STATE_AGENCY = "PROCESS_THROUGH_STATE_AGENCY"
    RECEIVE_CREDENTIALS = "RECEIVE_CREDENTIALS"
    COMPLETE = "COMPLETE"


class OcrStatus(StrEnum):
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ReviewReasonCode(StrEnum):
    BOTH_ROUTES_CHECKED = "BOTH_ROUTES_CHECKED"
    NEITHER_ROUTE_CHECKED = "NEITHER_ROUTE_CHECKED"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    INVALID_WR_NUMBER_FORMAT = "INVALID_WR_NUMBER_FORMAT"
    COMPANY_MISMATCH = "COMPANY_MISMATCH"
    LOW_OCR_CONFIDENCE = "LOW_OCR_CONFIDENCE"
    OCR_FAILED = "OCR_FAILED"
    OCR_FAILED_OR_UNKNOWN_STATUS = "OCR_FAILED_OR_UNKNOWN_STATUS"
    WORK_REQUEST_NOT_FOUND = "WORK_REQUEST_NOT_FOUND"
    SINGLE_PAGE_PDF = "SINGLE_PAGE_PDF"
    MISSING_CHECKLIST_ITEM = "MISSING_CHECKLIST_ITEM"
    CP_SUITE_ERROR = "CP_SUITE_ERROR"
    UNEXPECTED_ERROR = "UNEXPECTED_ERROR"


class MissingChecklistItemPolicy(StrEnum):
    REVIEW = "review"
    SKIP = "skip"
